def main():
    output = open("test.txt", "w")
    output.write(chr(186))
    output.write(chr(180))
    output.write(chr(194))
    output.write(chr(194))
    output.write(chr(200))
    output.write(chr(42))
    output.write(chr(216))
    output.write(chr(200))
    output.write(chr(206))
    output.write(chr(194))
    output.write(chr(178))
main()